### ISSUE TITLE
[REQUEST] Add custom badges

### ISSUE THREAD

**Issue by whyakari** [ziadOUA/m3-Markdown-Badges#14]
## How do I add custom badges? 

for example, I wanted to use m3 in these badges below:
> ![Screenshot](https://github.com/ziadOUA/m3-Markdown-Badges/assets/58480908/474e59bd-e7a8-446e-a3a4-3df6ec67f122)

## something like:
> ![badge-generator](https://raw.githubusercontent.com/MichaelCurrin/badge-generator/master/docs/_media/sample.png)
> - https://github.com/MichaelCurrin/badge-generator

> where in this interface, we would support the M3 type badge.

**Comment by ziadOUA** [comment]
Hello,
Your idea is interesting, but I'm not sure if I will add this.
As you showed in your example, the "Release" badge could be added (like the "Issues" and "Stars" badges already available).
The localization (in your case Weblate), the Telegram badge and the GPL v2 license can be added as static badges.

It could be a very interesting project to work on though, if this repository gains more users.
Thanks

**Comment by whyakari** [comment]
> Hello, Your idea is interesting, but I'm not sure if I will add this. As you showed in your example, the "Release" badge could be added (like the "Issues" and "Stars" badges already available). The localization (in your case Weblate), the Telegram badge and the GPL v2 license can be added as static badges.
> 
> It could be a very interesting project to work on though, if this repository gains more users.
> 
> Thanks

anyway, thx!!
