### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by Impre-visible** [ziadOUA/m3-Markdown-Badges#2]
Can you add :
C++
C#
Typescript
PHP
Swift
Java
Go
SQL
Ruby
R
Rust
Perl
Kotlin

and more frameworks like : 
React JS
React Native
Django
Angular
VueJS
jQuery
Laravel

and others things like : 
NPM
NuGet
Yarn

others contact : 
Discord
Mail (not gmail)

I thing this are the principals things to add

**Comment by ziadOUA** [comment]
I'm working on it.

PS : There is already npm
