### ISSUE TITLE
Add the Docsify logo

### ISSUE THREAD

**Issue by gensart-x** [ziadOUA/m3-Markdown-Badges#28]
Hi, 
I see your work is great here, I'll star that ! 😁

I also hoped that you can add for Docsify too. Or if you may have the tool to create a new one for me to be able to, please let me know. Thank you so much.

**Comment by ziadOUA** [comment]
Hello and Thanks !

I will add Docsify soon, but a tool to make them will be more complicated to do, considering the font I'm using is owned by Google.
I'm planning on using [Inter](https://github.com/rsms/inter) in the future, which is open source, and shouldn't cause problems if used in such a tool.

**Comment by gensart-x** [comment]
Thanks for the addition, I love that 💖
