### ISSUE TITLE
Add more icons

### ISSUE THREAD

**Issue by deleau-victor** [ziadOUA/m3-Markdown-Badges#5]
Your work is very qualitative, keep it up !

you can add :

In Language :
- GraphQL
- Dart

In database :
- PostgreSQL
- MariaDB
- CouchDB
- Oracle
- Cassandra
- Supabase
- Firebase
- fix MongoDB

In Framework :
- Next JS
- Nest JS
- Solid JS
- Gatsby
- Expo
- Astro JS
- Symfony
- Flutter

In Library :
- Axios
- Redux
- Styled Component
- JWT
- Prisma
- TypeORM
- Sequelize
- Apollo GraphQL

In Design :
- Adobe Xd
- Adobe illustrator
- Adobe Photoshop
- Adobe InDesign

In OS :
- Debian
- Ubuntu

Other :
- Docker
- Prettier
- Jest
- Eslint
- Postman
- Vite
- Trello
- Notion

**Comment by ziadOUA** [comment]
Thanks for the compliment !
I'm going to start making them
