### ISSUE TITLE
Add stars Badge!

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [ziadOUA/m3-Markdown-Badges#8]
Is it possible to add a badge that shows the number of stars from a repo? (a pastel Purple would be a nice color! but preferably editable)

**Comment by ziadOUA** [comment]
Hi @TeaEndsAcronyms ! Thanks for the suggestion.
Sadly, _as for now_ I cannot add this badge since I am focusing on static badges.

If you have any idea on how to create this badge, don't hesitate.

**Comment by TeaEndsAcronyms** [comment]
To be honest I don't know lol. Sorry I can't be of help, but if you end up making it that would be cool! :)

**Comment by ziadOUA** [comment]
Hello @TeaEndsAcronyms,

I have managed to add the stars badge !
I still haven't added documentation about how to add it, but you can add yours (and also test it) : 

`<img src="https://m3-markdown-badges.vercel.app/stars/1/1/<github-username>/<repo>"`

You can change the color of the badge by changing the first number (12 different styles), and you can change the variant of the badge (1 to 3, similar to the other static badges)

Example : 

<img src="https://m3-markdown-badges.vercel.app/stars/10/2/TeaEndsAcronyms/Material-You-Apps">

`<img src="https://m3-markdown-badges.vercel.app/stars/10/2/TeaEndsAcronyms/Material-You-Apps">`

**Comment by TeaEndsAcronyms** [comment]
Thanks, these look really good!
